export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_COTEGORIES = "GET_ALL_COTEGORIES";
export const PRODUCT_ID_FILTER = "PRODUCT_ID_FILTER";
export const PRODUCT_ID_SORT = "PRODUCT_ID_SORT"