export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const PRODUCT_ID_FILTER = "PRODUCT_ID_FILTER";
export const PRODUCT_ID_SORT = "PRODUCT_ID_SORT";
export const PRODUCT_NAME_FILTER = "PRODUCT_NAME_FILTER";
export const PRODUCT_NAME_SORT = "PRODUCT_NAME_SORT";